### ISSUE TITLE
Can't get FromContent to work with payload

### ISSUE THREAD

**Issue by maximuss** [tomkuijsten/restup#100]
I have tryed for some time now to get the [FromContent] to work with a POST and a Json payload, but everytime i get a 400 Bad Request. I hope there is a log file, but i just cant seem to locate it :(

What i have is this method:
```
       [UriFormat("/gardenlight/activtime/save")]
        public IPostResponse SetActivTime([FromContent]string gardenLightStorage)
        {
           //Doing some stuff
           return new PostResponse(PostResponse.ResponseStatus.Created);
        }
```
With this call:
`http://pi_dev01:20000/api/gardenlight/activtime/save` as POST and `Content-Type: application/json`
and this json payload:
```
{
  "EndTime": "0001-01-01T00:00:00.0000001",
  "LuxTurnOn": 1
}
```
but the method is never hit - i have error somewhere, but i just cant find it!
BUT if i call the method with a empty body, then the method IS hit....

Best Regards

Bjarne Pedersen

**Comment by tomkuijsten** [comment]
Just a quick response. You ask for a string in your method, but send an object with two properties. You should create an type with those two properties and use that one as method parameter type.

**Comment by maximuss** [comment]
I have been working with integration and rest api's for the last year - i should have known it!
It's working now and i have used that method everyday the last year.... talking about feeling like a noob now ;)
Thank you for your quick response.
