### ISSUE TITLE
Why don't we use the WebListener?

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#105]
I'm just a bit confused, I thought I searched for this package a long time but there was nothing compatible with Windows IoT. But according to [this post](https://github.com/aspnet/Home/issues/1110), the[ Microsoft.Net.Http.Server ](https://www.nuget.org/packages/Microsoft.Net.Http.Server/) package should work on Win10IoT.

**Comment by Jark** [comment]
I think that's running dnx / core applications directly on the raspberry pi (so not through uwp). Last time I looked the ARM version of .net core was still quite buggy. Once .net core does work on the windows 10 iot PI restup becomes obsolete since we'll have access to full asp .net :)

**Comment by tomkuijsten** [comment]
You are correct, as always :) Just read that the ARM support of net core is planned for Q1 2017:

https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by tomkuijsten** [comment]
Got ASP.NET core [working](http://www.devvy.nl/?p=170) on Win10IoT, will take some time before it's stable I guess.

**Comment by tomkuijsten** [comment]
I'll close this issue, not on the roadmap now. Will open it again when usefull. @Jark  agree?

**Comment by Jark** [comment]
@tomkuijsten agreed :)
