### ISSUE TITLE
FromBody attribute changed, documentation needs update

### ISSUE THREAD

**Issue by stefaanv** [tomkuijsten/restup#106]
It seems the FromBody attribute has changed into "FromContent".
This change is not yet reflected in the documentation.

**Comment by Jark** [comment]
Thank for reporting this @stefaanv.

Have just modified the wiki (https://github.com/tomkuijsten/restup/wiki/RestRouteHandler-details/373dee5d4de5b9c13ed1269b4c99677073725771).
