### ISSUE TITLE
Why that server don't work in cell phones?

### ISSUE THREAD

**Issue by Jaedson33** [tomkuijsten/restup#109]
I can't make that work in my Lumia, why?

**Comment by Jark** [comment]
Hi @Jaedson33,

Can you be a bit more specific? What have you tried specifically?

Have you tried running the demo or your own application?

**Comment by Jaedson33** [comment]
Sorry, but I solved that yesterday.
I was trying to connect to my phone's server using its host name, but it wasn't working. Now, its working because I'm using the phone's IP.
