### ISSUE TITLE
Add ASP support

### ISSUE THREAD

**Issue by Jaedson33** [tomkuijsten/restup#116]
I can't make na aspx work in StaticFileHandler, but why?

**Comment by Jark** [comment]
Hi @Jaedson33,

Can you tell us a bit more about what you are trying to accomplish? The static file handler will simply post the file back to the client with the mime type based off the extension.

If you want to return the .aspx files as html you can do that by instantiating the StaticFileHandler with a `MimeTypeProvider` with the .aspx file added to the available mime types.

In any case it's not going to run the .aspx file itself, but will only be able to show it as html, text. 

It looks like asp .net core is getting to the state were it's able to run on the pi (see: http://www.devvy.nl/?p=170) and going to be run in a stable fashion.

Hope this helps,

Jark

**Comment by Jark** [comment]
Closing this issue since there have been no replies for nearly a month.
