### ISSUE TITLE
Access from local machine over localhost or 127.0.0.1

### ISSUE THREAD

**Issue by emulic** [tomkuijsten/restup#125]
Hi,

is there any way to reach the rest service from another UWP or other app running on the same machine as the UWP app hosting the rest service? I'm always getting timeout either if I use IP address 127.0.0.1, localhost, IP address of my machine or host name. If I try to call the rest service from another machine everything works fine.

**Comment by Jark** [comment]
Hi @emulic,

When I looked at this last this does not seem to be possible, please refer to point 1 of the FAQ (https://github.com/tomkuijsten/restup/wiki/FAQ).

**Comment by emulic** [comment]
thanks!

**Comment by DennisSc** [comment]
On w10 IoT core, you can enable inbound loopback exemptions with a registry key:

> reg add hklm\system\currentcontrolset\services\mpssvc\parameters /v IoTInboundLoopbackPolicy /t REG_DWORD /d 1
> 
> Then you need to run (for outbound connection):
> CheckNetIsolation.exe LoopbackExempt -a -n=< AppContainer or Package Family>
>  
> For example
> CheckNetIsolation.exe LoopbackExempt -a -n=IoTCoreDefaultApp_1w720vyc4ccym
>  
> For inbound connections the following process needs to be created (and keep running).  I believe this part is new in 14393 and beyond.
> checknetisolation LoopbackExempt -is -n=<package family name: like(NodeScriptHost_dnsz84vs3g3zp)>
> You can’t run an appx app from the command-line.  You can use iotstartup list to get the list of package family names, and then use iotstartup run to launch a given app from the command line.

see https://social.msdn.microsoft.com/Forums/en-US/bd84318f-25d3-425c-a631-de9090aaa60e/loopback-access-failing-14393?forum=WindowsIoT#41ace723-9bad-4e04-90b1-077a1665f2dc

**Comment by sibarsoumi** [comment]
So, is debugging on the same device not possible in any way? Does one always need a second device for debugging!?
