### ISSUE TITLE
Would this work as a replacement for HTTPListener?

### ISSUE THREAD

**Issue by ta-vroom** [tomkuijsten/restup#126]
I had a server which listened for JSON, but I had to start over when I moved to UWP. Any chance this could fill that role?

**Comment by tomkuijsten** [comment]
Depends a bit on what you want to achieve.

**Comment by ta-vroom** [comment]
Literally just receive JSON data from a webapp/program. Just a bit confused on REST vs Sockets and which would be most appropriate.

**Comment by tomkuijsten** [comment]
That's really easy to achive, take a look at the sample code or the wiki on how to achieve this.

**Comment by ta-vroom** [comment]
alright, thanks for the help.

**Comment by ta-vroom** [comment]
Is it possible to somehow get the data, without dealing with the uri? If restup won't work, I can write my own socket server. Just having trouble isolating the data from the header.

**Comment by Jark** [comment]
Hi,

Restup is meant as a REST server, however if you want to just use the socket to http request functionality you could implement a custom `IRouteHandler` (https://github.com/tomkuijsten/restup/blob/master/src/WebServer/Models/Contracts/IRouteHandler.cs) and use that in httpServer.RegisterRouteHandler.

Cheers,

Jark

**Comment by ta-vroom** [comment]
Thanks for the help.
