### ISSUE TITLE
Optimize the Restup

### ISSUE THREAD

**Issue by jaedson-barbosa** [tomkuijsten/restup#132]
Hi, I see you like to support the first version of UWP. But I think you should focus on the latest versions of Windows. In my opinion, the minimum version should be the Anniversary Update. What do you think? Can I change the minimum version and optimize the code?

I just need to know that to start the work. After all, I want the PR to be approved.

**Comment by Jark** [comment]
Hi @JaedsonBarbosa,

Can you tell me what the improvements would be? Are there performance improvements or code clarity improvements?

If possible I'd like to keep as low a version as possible for restup, to ensure a lot of people are able to use it, unless there is a compelling reason I would advocate against updating it.

You should be able to add restup to an application which is running the latest sdk version, and then restup should run with all the performance improvements of that version.

Cheers,

Jark

**Comment by Jark** [comment]
Closing due to no reply
