### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by ThomasVilliger** [tomkuijsten/restup#135]
Hi there

Your Webserver works great on Raspberry Pi with Windows 10 IoT but not on my development PC where I have Windows 10. Am I doing something wrong or is this the way it is?

Thanks!

**Comment by dm-CaT** [comment]
@ThomasVilliger, you can follow the steps from [this](https://github.com/tomkuijsten/restup/issues/127) request to start Restup Server locally.
