### ISSUE TITLE
Support parameter arrays

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#16]
I once found a suggestion on SO to implement it as html handle arrays in an url. Looks like the right way to handle arrays for REST services.

**Comment by tomkuijsten** [comment]
I started a discussion on the REST guideline GitHub:

https://github.com/tfredrich/RestApiTutorial.com/issues/34

**Comment by tomkuijsten** [comment]
After reading a lot of blog posts and SO questions, I believe that the ```?id=1,2,3``` would be the best approach.

**Comment by Jark** [comment]
Could you elaborate a bit more? 

For instance, how would you send this array over the wire using this method?

```javascript
var lines = ["Today, I'm doing things", "Tomorrow, I'm free"];
```

**Comment by tomkuijsten** [comment]
```
/api/control/settings?id=Today%2C%20I&#39;m%20doing%20things,Tomorrow=%2C%20I&#39;m%20free
```
You should always html encode your string.

While I'm thinking of it, the ```,``` might not be the best separator. If you want to send decimals, it would be nice if a ```,``` wouldn't have to be encoded (for url readability). A ```;``` might be a better solution (as [StackOverflow](https://api.stackexchange.com/docs/questions-by-ids#order=desc&sort=activity&ids=123%3B1234&filter=default&site=stackoverflow) is using it).

Could be used as query parameter (?ids=1;2;3) or url segment (/api/ids/1;2;3/).

I do see 1 problem. The html encoded string contains ```&``` character, which will mess with the query parameter chaining:

_/api/control/settings?id=Today=%2C%20I**&**quot;m%20doing%20things**&**max=23_

**Comment by Jark** [comment]
Semicolons do seem to work a bit nicer indeed.

The `&` character should not have to mess up the query parameter encoding since all html encoded strings will end every encoded character with a `;`. 

So we could either write a parser that doesn't use regex, or we could simply url decode the string before using regex to match it up :)

**Comment by tomkuijsten** [comment]
I'm a bit confused about encoding strings, you could encode the character  ```"``` as ```&quot;``` and as ```%22```. Can all characters be encoded to a ```%``` variant? If so, the whole ```&``` issue can be avoided.

Ps: I can't find any big REST api using strings as an array. Yes, SO and TFS do allow tags as array, but those do not accept "problematic" characters in the first place.

**Comment by tomkuijsten** [comment]
Not so confused anymore :). The ```%``` encoding seems to be the way to encode characters for an [URI](https://en.wikipedia.org/wiki/Percent-encoding) the ```&xxx;``` notation is for html documents.

I've created some unit-tests around the cases I wish to support (and they all fail ofcourse). One tiny thing, I forgot to commit yesterday, do that tonight.

**Comment by tomkuijsten** [comment]
@Jark care to review?

**Comment by Jark** [comment]
Sure, will do, will probably be a bit later today.

**Comment by Jark** [comment]
@tomkuijsten this is fixed now right?

**Comment by tomkuijsten** [comment]
Jep
