### ISSUE TITLE
Should we add default /api/ prefix to all url's

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#18]
Or as a configurable prefix

**Comment by tobiasstraub** [comment]
In our project we don't use /api/ prefix, because the domain name is the API access. But a feature like this would be great, for API versioning, like https://example.com/v1/endpoint.

**Comment by tomkuijsten** [comment]
I like the idea of versioning, but wouldn't that be something to put on your controller with ie an attribute? Something like this:

```
[RestController(Version:=1)]
```

I still believe that a separate prefix will be useful.

**Comment by tobiasstraub** [comment]
I think an attribute on controller makes it very difficult. When you have a bigger API, you have many Controllers with possibly different versions. In practice you mark with an API version update the complete API as a new version. So I think a prefix is very useful. Many big API player use this kind of versioning. By the way: On [apigee](https://pages.apigee.com/rs/apigee/images/api-design-ebook-2012-03.pdf) you can find a short eBook with best practices for API Design.

**Comment by tomkuijsten** [comment]
But if you have controllers with different versions in one project, how would the prefix help? If you want to store the version there, you will only have one version number for the complete service. Cause my idea was to have a prefix for the entire service, not a prefix for one controller.

**Comment by tomkuijsten** [comment]
Prefix is available on the constructor of ` RestWebServer `
