### ISSUE TITLE
Return message for Post and Put

### ISSUE THREAD

**Issue by tobiasstraub** [tomkuijsten/restup#19]
Hi @tomkuijsten,
is it possible to define for PostResponse (instead of the locationRedirectUri) and for PutRequest a return message? E.g. {“developerMessage” : “Error. Wrong JSON schema.”}
This would be really great. :-)

**Comment by tomkuijsten** [comment]
Possible, yes :) But the [RestApiTutorial](https://github.com/tfredrich/RestApiTutorial.com) state that a Post can never return values, a Put can. I'm not saying that's the truth, but I like to hear why a return value would be valid.

**Comment by tobiasstraub** [comment]
I think it is often useful to say the developer what's wrong with the requested POST. But I have just looked how Facebook handle this. I haven't seen that Facebook give a response to a POST. But by PUT requests I have seen that they often give the developer a feedback via a return JSON.

**Comment by tomkuijsten** [comment]
Just committed 4d6390d3508d5f65aa1ae8af425c53df217c119c which contains the extension of the PUT messages, accepting body data now.
I don't quite understand why a PUT should be allowed a return message and a POST don't, do you know why?

**Comment by tomkuijsten** [comment]
POST also supports a body now
