### ISSUE TITLE
POST and PUT requests via Client Framework don't work correct

### ISSUE THREAD

**Issue by tobiasstraub** [tomkuijsten/restup#20]
I have tested my API, I have created with restup the last time via [cURL](http://curl.haxx.se/). Via cURL all works fine. Now I have on client side setup the [RestSharp Framework](http://restsharp.org/) to send requests on restup server. GET and DELETE requests works. But POST and PUT don't work. Because it works with cURL, I suspected the fault on client side. But after I tested all, I think the fault must be on restup side.

**My Test Scenario with cURL for PUT (all works fine)**
`curl -v -i -H "Content-Type: application/json" http://minwinpc:80/staticip/v4 -X PUT -d @data.json`

data.json (Example data)
`{"ipV4":"192.168.5.2","subnetV4":"192.168.255.255","gatewayV4":"192.168.0.1"}`

Tracking Client Ethernet via [Wireshark](https://www.wireshark.org/) (you can see, all works fine)
![screen1](https://cloud.githubusercontent.com/assets/4949800/11325135/5cc519f6-9146-11e5-9c21-5737b576217b.jpg)
Received 200 status code

**My Test Scenario with RestSharp for PUT (Problem)**
```
public void Update(ModelObj obj) {
 var client = new RestClient("http://minwinpc/");
 var request = new RestRequest("staticip/v4", Method.PUT) { RequestFormat = DataFormat.Json };
 request.AddBody(obj);
 client.Execute(request);
}
```

Tracking Client Ethernet via [Wireshark](https://www.wireshark.org/) (It shows good)
![screen2](https://cloud.githubusercontent.com/assets/4949800/11325215/fea0ec22-9147-11e5-85be-6f256fb26699.jpg)
I can't see any difference to the cURL request. Ok, RestSharp adds a little bit more meta data in Header but I don't think that's a problem.

**So I show in the restup code and see the following**
In file HttpServer.cs there is called a method GetRequestString(argsSocket) and returned the request string. I have set a breakpoint a line below on `var result`. When I show the request var there is the content: `"PUT /staticip/v4 HTTP/1.1\r\nAccept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml\r\nUser-Agent: RestSharp/105.2.3.0\r\nContent-Type: application/json\r\nHost: minwinpc\r\nContent-Length: 61\r\nAccept-Encoding: gzip, deflate\r\nConnection: Keep-Alive\r\n\r\n"`

You can see the JSON body is missing. So Bad Request will be returned. But WHY is the JSON body missing? - On the Wireshark screenshot you can see there was sent.

So I have a long time debugged. The fault must be depending on the runtime, because:
When I set the breakpoint one line above on `string request = ...` and stepped into until the debugger is on position `var result = ...` the request is complete:
`"PUT /staticip/v4 HTTP/1.1\r\nAccept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml\r\nUser-Agent: RestSharp/105.2.3.0\r\nContent-Type: application/json\r\nHost: minwinpc\r\nContent-Length: 61\r\nAccept-Encoding: gzip, deflate\r\nConnection: Keep-Alive\r\n\r\n{\"ipV4\":\"0.0.0.1\",\"subnetV4\":\"0.0.0.0\",\"gatewayV4\":\"0.0.0.0\"}"`

So I suspect the fault must be in GetRequestString on file HttpServer.cs but I can't find the fault.

Any ideas?

**Comment by tomkuijsten** [comment]
You're just one step ahead of me, cause I got the same problem Friday. Thanks for all your research. I changed my response from Ok to NoContent and it all went fine, now I understand why. I'll start investigating now what is exacatly going wrong.

**Comment by tomkuijsten** [comment]
Hmm I was a bit too quick with my response. My problem had something to do with the output, you talked about the input. Different problem I guess.

I tried to reproduce the problem with your request string, but I couldn't get it to fail. I used the sample project and deployed that one on my pi. I used fiddler to send your request and no matter what I did, the `GetRequestString` returned the right request. Did the problem occur when you ran in "Release" configuration, or only in "Debug"?

I also searched for ways to read the IInputStream, but this seems like the appropriate solution. If you know any other way, or have suggestions for refactoring, I'd love to hear them.

**Comment by tobiasstraub** [comment]
Maybe we should look the HTTP header in more detail. RestSharp add some header information which are maybe stopping the correct processing. You send your request with fiddler, and all works fine? I tested via cURL and it works also fine. Only a request via the RestSharp framework didn't processing correct. But in alle cases the JSON body is the same.

Have you ever tested via RestSharp framework? Should I upload a simple solution with the test scenario?

**Comment by tomkuijsten** [comment]
Never used RestSharp, but it looks pretty simple to use. I'll create some sample code to test with.

Did you check the request from RestSharp with Fiddler?

**Comment by tomkuijsten** [comment]
I just tried communicating with the RestSharp lib and that worked fine. At least the GET and PUT. I'm working on a test for POST, but I don't see why that would be different then PUT.

**Comment by tobiasstraub** [comment]
Sorry for the late response. Can you upload your test code?

**Comment by tomkuijsten** [comment]
Just tried a POST (with the sample WebServerHostTest project) and works like a charm. This is the code I used

```cs
    class Program
    {
        static void Main(string[] args)
        {
            var client = new RestClient("http://192.168.1.123:8800/");
            var request = new RestRequest("frombody", Method.POST) { RequestFormat = DataFormat.Json  };
            request.AddBody(new FromBodyData() { Counter = 10 });
            var response = client.Execute(request);
        }

        public class FromBodyData
        {
            public int Counter { get; set; }
        }
    }
```

**Comment by tomkuijsten** [comment]
Sorry, forgot to commit the new POST sample controller. Just did and the test code above should work now.

**Comment by tobiasstraub** [comment]
Thank you so much. I'll check this tomorrow early. :-)

**Comment by tomkuijsten** [comment]
No problem, thanks for all the feedback, helps me a lot. I hope the problem is solved.

**Comment by tobiasstraub** [comment]
Today we have tested the scenario with alpha3 in two different test networks again. We already have the same issue described above. If we slow down the program flow in restup artificially, it works (see for loop with debugging output). On weekend, I will try again to find out what is going wrong here.

```
private async void ProcessRequestAsync(StreamSocketListener sender, StreamSocketListenerConnectionReceivedEventArgs args)
        {
            await Task.Run(async () =>
            {
                try
                {
                    for (var i = 0; i < 500; i++) { System.Diagnostics.Debug.WriteLine("non"); }

                    string request = await GetRequestString(args.Socket);

                    var result = await HandleRequest(request);

                    await WriteResponseAsync(result, args.Socket);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine($"Exception while handling process: {ex.Message}");
                }
                finally
                {
                    try
                    {
                        // Lets make sure the socket will always close
                        args.Socket.Dispose();
                    }
                    catch { }
                }
            });
        }
```

**Comment by Jark** [comment]
I would try uncommenting the args.Socket.Dispose() line. Looking at the original code (https://github.com/ms-iot/samples/blob/b1e1608931a42bc72c76b7d44e55f2731b639c8a/App2App%20WebServer/WebServerApp/WebServerTask/BackgroundTask.cs#L112) it's not disposed.

There might be a possibility that the open socket is reused for subsequent connections from the same source.

**Comment by tobiasstraub** [comment]
@Jark Thanks. It was worth a try. But did not help. Only the artificial delay before the `input.ReadAsync(...)` helps.

```
await Task.Delay(1000);
                while (dataRead == BUFFER_SIZE)
                {
                    await input.ReadAsync(buffer, BUFFER_SIZE, InputStreamOptions.Partial);
                    request.Append(HttpRequestStringEncoding.GetString(data, 0, data.Length));
                    dataRead = buffer.Length;
                }
```

**Comment by tomkuijsten** [comment]
Can you try something for me? I was cycling to work just now (funny that the best idea's are born while cycling or taking a shower and not at work :) ) and tried to understand what is going wrong. The delay proofs that it has something to do with async streaming of any kind. Could you change this line in HttpServer.GetRequestString:

```cs
await input.ReadAsync(buffer, BUFFER_SIZE, InputStreamOptions.Partial);
```

To this

```cs
await input.ReadAsync(buffer, BUFFER_SIZE, InputStreamOptions.ReadAhead);
```

**Comment by tomkuijsten** [comment]
Hmm just found this post and it sounds like he has the same problem:

http://stackoverflow.com/questions/32297416/c-sharp-http-server-using-streamsocketlistener-the-option-inputstreamoptions-p

**Comment by tomkuijsten** [comment]
After reading some articles and talking to developers I've decided to implement a solution. The input stream could be read at once, but because of it's streaming nature, you will never now for sure if nothing else will come in. There is no way to determine when the sender is finished with it's request. Luckily for us, we only accept http requests, so we do have some idea of what a request will look like.

I have implemented the following rules:
 - A http request should have a \r\n\r\n sequence (as specified by the [http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html](http standard))
 - When this \r\n\r\n is received, the content-length is searched for
 - If the length is available, that will be used to check if the request is complete yet
 - If the length isn't available, the request is considered ready
- In all cases, when the stream is empty three times, it will mark the request as "Bad Request"

It's impmlemented in a new class "HttpRequestStreamReader" and extended unit-tests are available. I hope that this will tackle the problem.

**Comment by tobiasstraub** [comment]
Works now, really good job! :-)

Your first idea with changing `InputStreamOptions.Partial` to `InputStreamOptions.ReadAhead` didn't work. I had the same idea, days ago, and so I tried this. The idea with checking the content-length is perfect. Thanks for your Implementation of this feature.

**Comment by tomkuijsten** [comment]
Thank you for finding it :). I will improve this implementation with the help of Jark, he already did some great OO stuff for this feature in his branch. It's now parsing the data multiple times, which is a waste of precious cpu cycles. Anyway, this shouldn't affect you.

**Comment by Compactis** [comment]
Hello, I think I understand well how to arrive to fulfill the condition. Could you tell me somebody write all that code while (allDataRead). How does it perform allDataRead.
Thank you very much.

**Comment by tomkuijsten** [comment]
I don't really understand your question @Compactis , could you elaborate a bit? Might be better to start a new issue as this one is closed.
