### ISSUE TITLE
Support parameters in RestController constructor

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#25]
It's inconvenient that you can't pass parameters to the constructor of the RestController, there should be some way to inject them.

**Comment by tomkuijsten** [comment]
Already fixed

**Comment by stefaanv** [comment]
How can I inject dependencies into the constructor ?
When I add the parameters to the RegisterController() function, the framework doesn't respond to calls anymore.

**Comment by WattsC-90** [comment]
@tomkuijsten  Have you got an example/sample on how you did this? Just so I know I am going down the right path with what I am doing to get DI into my app using the RestUp package.

**Comment by Jark** [comment]
@WattsC-90 when you call RestRouteHandler.RegisterController you can pass in the objects. Those objects will then be used to construct the controller every time a call comes in.

**Comment by WattsC-90** [comment]
@Jark so less Dependency Injection style? More concrete, in one place? Would RestUp support a DI container? e.g.: Unity/TinyIoC?

**Comment by Jark** [comment]
Yeah, it's more passing in the instances themselves into the RegisterController methods. So the DI resolving would have to happen when you are registering your controllers.

e.g.

```
var restRouteHandler = new RestRouteHandler();
restRouteHandler.RegisterController<UsersController>(unityContainer.Resolve<IUserStore>());
```

There's also an overload of RegisterController that takes a Func<object[]> args that's deprecated, but I think properly implementing DI would be better.

So how about we add support to plug in a DI like asp .net does (with IDependencyResolver -> https://msdn.microsoft.com/en-us/library/system.web.mvc.idependencyresolver(v=vs.118).aspx) would that work?

**Comment by WattsC-90** [comment]
@Jark  not a bad idea for the IDependencyResolver interface, perhaps be interesting to see how Ninject handles injection into the OWIN/ASP.Net controllers. I dont know enough about how it works (always treated it as blackbox), but might be a place to start. If not, implementing the IDependencyResolver interface seems reasonable! =]

**Comment by WattsC-90** [comment]
@Jark thinking about it.. IDependencyResolver definitely the way to go, Ninject is the implementation of that. So the RestUp code would have a `.RegisterDependencyResolver<Type>()` or `.RegisterResolver(resolver)` method, that would then be used internally to get the arguments for controllers that are called "on the fly"?

**Comment by dm-CaT** [comment]
Regarding DI. I faced an issue - there is no possibility to declare controller's constructor with interface as a parameter, UWP denies that. That's why I declared constructor with a parameter of object type. And then cast it to interface. Here is an example
```
    [RestController(InstanceCreationType.Singleton)]
    public sealed class ValvesController
    {
        private IValveManager _valveManager = null;
        public ValvesController(object valveManager)
        {
            _valveManager = valveManager as IValveManager;
        }
    }

```
To inject this I used unity in startup task
```
_container.RegisterType<IValveManager, ValveManager>();
restRouteHandler.RegisterController<ValvesController>(_container.Resolve<IValveManager>());
```
It looks not so good. Can someone propose any solution to avoid using an object as parameter?

**Comment by Jark** [comment]
@WattsC-90 yeah, something like that. Current design I'm thinking off:

1. the existing RegisterController will error as before if you haven't configured a custom IDependencyResolver, you have a parameterised constructor and you don't pass the correct parameters in.
2. if you have a custom IDependencyResolver configured, then that will be used to instantiate the RestController, any configured `InstanceCreationType` (Singleton/PerCall) behaviours will be ignored (or maybe passed into the Resolve method?) 

@dm-CaT Do you get the error ""No constructor found on {typeof(T)} that matches passed in constructor arguments." ? I see that there's a bug in restup where it expects you to match the exact type of the constructor, this will of course not work properly when you use interfaces. I'll raise a separate issue for this, should be a fairly simple fix.

**Comment by dm-CaT** [comment]
@Jark this code works well without any errors. It just looks ugly.

**Comment by WattsC-90** [comment]
@Jark seems like a good plan to me, @dm-CaT what code looks ugly?

**Comment by dm-CaT** [comment]
@WattsC-90 constructor of controller with object-typed parameter which has to be cast to interface inside constructor body. I didn't find any other solution how can I inject parameters in controller.

**Comment by WattsC-90** [comment]
@dm-CaT Thanks for the clarification, wasnt sure which bit you meant! :)
