### ISSUE TITLE
Server crashes when used in headless app

### ISSUE THREAD

**Issue by ManniAT** [tomkuijsten/restup#26]
I created a new Solution (Windows IoT - Background) added a class library (to host my controllers) and added restup via NuGet to the class library.
In the Background app I did this:

```cs
public sealed class StartupTask : IBackgroundTask {
	private RestWebServer _webserver;
	public void Run(IBackgroundTaskInstance taskInstance) {
		BackgroundTaskDeferral deferral = taskInstance.GetDeferral();
		_webserver = new RestWebServer(8800);
		_webserver.RegisterController< DummyController>();
		ThreadPool.RunAsync(workItem => {
			_webserver.StartServerAsync();
			//server.Start();
		});
	}
}
```

Further I enabled Client+Server in the manifest.
Runnig this on my RapsBerry brings up the server (Message in Output).
When I make a request the background app silently (no exceptions) terminates.

Doing the same on a headed app works as expected.

I attached the sample project - maybe this helps to better understand what I'm doing.
[BackgroundApplication1.zip](https://github.com/tomkuijsten/restup/files/101827/BackgroundApplication1.zip)

**Comment by tomkuijsten** [comment]
I'll take a look at it. I already got it working in headless mode, so it should be possible.

**Comment by ManniAT** [comment]
Maybe I just missed some setting / ref.... in my solution.
I like your project and really would like to use it.

**Comment by tomkuijsten** [comment]
I'm working on a headless sample, hang on.

**Comment by ManniAT** [comment]
I'm very sorry for this...
Just checked my code one again - and found the problem.

I did:

public sealed class StartupTask : IBackgroundTask {
    private RestWebServer _webserver;
    public void Run(IBackgroundTaskInstance taskInstance) {
        BackgroundTaskDeferral deferral = taskInstance.GetDeferral();
        _webserver = new RestWebServer(8800);
...

The problem here is that deferral is a local variable.
And (for some reason) this thing was alive till I made a call to the WebServer.
Several assemblies got loaded - which must have triggered GC - and this (of course) remove the deferral - shutting down the app.

A simple change to 

public sealed class StartupTask : IBackgroundTask {
    private RestWebServer _webserver;
    BackgroundTaskDeferral deferral;
    public void Run(IBackgroundTaskInstance taskInstance) {
        deferral = taskInstance.GetDeferral();
        _webserver = new RestWebServer(8800);
...

fixed everything - I confirm that WebServer is running in headless applications without problems.

**Comment by tomkuijsten** [comment]
Thanks for the info and I keep it open, because I'm doing the same thing you did with the deferral. Will fix it in the demo app.

**Comment by tomkuijsten** [comment]
Fixed in branche

**Comment by ManniAT** [comment]
Do you have a timeline when you merge / update nuget?

**Comment by tomkuijsten** [comment]
Merge already happened and the nuget package is updated to beta1 (indexing now, so could take a few hours before you can install).
