### ISSUE TITLE
Passing query string values

### ISSUE THREAD

**Issue by DamianMehers** [tomkuijsten/restup#28]
I've found I can pass query string values by escaping the question mark:

```C#
    [UriFormat("/GetTemperatures\\?start={start}&end={end}")]
    public GetResponse GetTemperatures(string start, string end) {
      Debug.WriteLine("Received request start " + start + " end " + end);
      return new GetResponse(GetResponse.ResponseStatus.OK);
    }
```

Would you like a pull request to escape it in code?

**Comment by tomkuijsten** [comment]
That's an interesting approach ☺. Pull request would be nice.

**Comment by DamianMehers** [comment]
[Here you go](https://github.com/tomkuijsten/restup/pull/29)

**Comment by tomkuijsten** [comment]
Thanks. I've just been sick a couple of days, I'll merge this soon.

**Comment by tomkuijsten** [comment]
Merged you're request. Might need some more rework to fully support all query parameter options.
