### ISSUE TITLE
Static contents

### ISSUE THREAD

**Issue by watashimeandeu** [tomkuijsten/restup#30]
There is any way to support static contents?

Ex:
[UriFormat("/public")] publish the requested file on a folder specified on server start.

Like:
StaticContents.Add(StaticContentBuilder.AddDirectory("public", @"contentFolder/subFolder"));

Thank you.

**Comment by tomkuijsten** [comment]
I've been playing with the idea before. Problem is that if you want to implement this correctly, it will take a whole lot of time which I don't have.

**Comment by tomkuijsten** [comment]
I have two pull request which adds static content handling, I'm reviewing both now, so it shouldn't be too long before this is supported.

**Comment by watashimeandeu** [comment]
Such a great news.
Thank you for the information.

**Comment by Jark** [comment]
The pull request has been merged: https://github.com/tomkuijsten/restup/pull/34.
