### ISSUE TITLE
Xml Serialization crashes when compiling in Native .NET

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#37]
When "Compile with .NET Native tool chain" project property is enabled, a xml response with a custom object throws an error (eg SingletonControllerSample.GetSingletonSampleValue).

```
Exception thrown: 'System.InvalidOperationException' in System.Xml.XmlSerializer.dll

Additional information: Xml_MissingSerializationCodeException, Devkoes.Restup.DemoControllers.SingletonControllerSample+WebserverInfo, XmlSerializer
```

**Comment by tomkuijsten** [comment]
Known "issues" with serialization:

https://msdn.microsoft.com/en-us/library/dn600165(v=vs.110).aspx#Step4

**Comment by tomkuijsten** [comment]
For the nuget package this is not really an issue as the package is build as AnyCPU which doesn't use the ".Net native tool chain". But it is a problem when using the toolchain. I couldn't find much information other then the link I posted and that following those guidelines runs into a XML_MissingSerializationCodeException, which is nowhere to be found on the internet (other then the [source](https://github.com/dotnet/corefx/blob/612855bed4249046229bc793b63176a6587d233a/src/System.Xml.XmlSerializer/src/System/Xml/Serialization/XmlSerializer.cs)).

I'm removing the RC1 milestone. This should be fixed if we decide to generate a .net native assembly in our nuget package.

**Comment by Clouvey** [comment]
I ran into an issue where debug reported an unsupported protocol when the browser tried to link to the device. I compiled with .NET Native tool chain turned on and it fixed the issue and now works great. I'm running with the latest version of all NuGet packages so this may have caused the issue. I also have everything set to build as native ARM in the Configuration Manager. (Note: full solution compiled this way and headless demo tested)  In any case it works great!  BTW Thanks for this code contribution Tom! Its going to be very useful.

**Comment by tomkuijsten** [comment]
Thanks for your feedback. Did you use the nuget package from the development branch? Or pulled and build the code yourself?

**Comment by Clouvey** [comment]
Pulled and built the code.
I had been looking for code I could use with the Raspberry Pi BME280 
weather module to display temperature and humidly from a web page.
Works great.
Thanks again for the code contribution.

**Comment by Clouvey** [comment]
Resolved issue where debug reported an unsupported protocol when the browser tried to link to the device when using the NuGet package.  Micro SD card on Raspberry Pi was corrupt / failing. My bad for using an old card. Replace with a new one and all is well.
