### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by HakanL** [tomkuijsten/restup#42]
Would be good to see errors for when files don't exist, etc.

**Comment by Jark** [comment]
Hi HakanL,

Sounds like a good plan, I think the project could definitely benefit from more logging at various places.

Do you have any experience with how the ms logging works on UWP? When I had a quick look it looked quite complicated and a logging framework like https://github.com/onovotny/MetroLog seemed necessary.

For a first try we can maybe just reference MetroLog directly, if the project gets more popular and people need different logging frameworks then we can introduce some kind of interfaces. What do you think?

Cheers,

Jark

**Comment by HakanL** [comment]
I was starting to use the Microsoft.Extensions.Logging (https://github.com/aspnet/Logging) in my project, but I can't say I was spending a lot of effort picking one. I like Serilog, but it doesn't support UWP (yet). I'll check out MetroLog. In general it would be good to just use an interface framework for logging and let DI resolve it.

**Comment by tomkuijsten** [comment]
This is an interesting option:

https://blogs.windows.com/buildingapps/2016/06/10/using-device-portal-to-view-debug-logs-for-uwp/

**Comment by tomkuijsten** [comment]
Do you have a PR ready @Jark?

**Comment by Jark** [comment]
Not yet! In my break later today I'll create a pull request for the interface project only, and will do a standard implementation as a separate pull request.

**Comment by Jark** [comment]
See -> https://github.com/tomkuijsten/restup/pull/76

**Comment by Jark** [comment]
Closing since it's fixed with #76
