### ISSUE TITLE
Add support for Accept-Encoding: gzip

### ISSUE THREAD

**Issue by Jark** [tomkuijsten/restup#43]
Now that we have support for files we should probably add support for gzip compression if the client requests it.

The approach that I'm going to take is to implement this on HttpServer level, so that it will compress the content back with the encoding that the client requests and sets the Content-Encoding level as a result.

In the process I might change the HttpServerResponse object into a RouteHandlerResponse to more firmly define that the route handler response is not the final response and that there will be some (further) processing involved.

**Comment by tomkuijsten** [comment]
Sounds like a plan. @chkr1011 told me he was working on a pull request for compression as well, might be interesting to contact him.

**Comment by Jark** [comment]
I've got a little prototype here: https://github.com/tomkuijsten/restup/compare/master...Jark:feature-add-support-for-compression which is working, but needs some refactoring to correctly adjust the content-length property.

**Comment by chkr1011** [comment]
Hi,
yes this feature is part of my implementation (and working correctly). But
I don't know when I can complete a pull request.

Code:
https://github.com/chkr1011/CK.HomeAutomation/blob/master/SDK/HA4IoT.Networking/HttpResponseSerializer.cs

Complete code (part of my Home Automation Solution):
https://github.com/chkr1011/CK.HomeAutomation/tree/master/SDK/HA4IoT.Networking

Best regards
Christian

2016-03-11 15:26 GMT+01:00 Jark <notifications@github.com>:

**Comment by Jark** [comment]
Hi Christian,

I don't mind completing the change in restup if you don't have the time to do it. It's not a difficult change to make.

Regards,

Jark
