### ISSUE TITLE
HttpServer

### ISSUE THREAD

**Issue by strehar** [tomkuijsten/restup#44]
Hello,

you might want to check [HttpServer library](https://github.com/strehar/HttpServer), that provides 
http requests, http responses, cookies, sessions, timers, json, two templating engines, one based on DotLiquid pot to Universal Apps and another based on simple string substitutions, dynamic web pages with template engines, custom URL listeners, 

To integrate with your rest api, minimal code would be

```
HttpServer server = new HttpServer();
server.AddPath("/api", restRouteHandler);
server.start();
```

There is demo project that shows more functionality.

**Comment by Jark** [comment]
Hey strehar,

Thanks for the link, from the features you mentioned I think we'd want to support cookies in restup, we already support custom url listeners, http requests, http responses and json.

The other features seem more like they shouldn't be part of a http server implementation but rather part of a framework and would most likely not be implemented in the core bit of restup but maybe as an extension of restup.

I am interested in seeing how you prove that your http server implements the http spec properly, do you use some kind of external testing framework for this? I couldn't discover any kind of tests in your repo.

Cheers,

Jark

**Comment by strehar** [comment]
Sessions should be part of server too, it's usefull to have them supported out of the box.

You can test server on the [REDbot](https://redbot.org/). I check it there, very usefull tool.

**Comment by Jark** [comment]
Had a look at it, seems quite useful, thanks :) 

Closing this issue, since it's not really a problem with restup. Feel free to link to this repo from your repo as a possible integration.

Cheers,

Jark
