### ISSUE TITLE
Allow for simple implementation of new Route Handler external to RestUp

### ISSUE THREAD

**Issue by HakanL** [tomkuijsten/restup#47]
I'd like to implement my own route handler (in my own code, not as part of RestUp) so it would be nice to have HttpServerResponse public so it can be instantiated from external code.

**Comment by tomkuijsten** [comment]
It currently can be instantiated by using the .Create methods, I don't understand the problem.

**Comment by HakanL** [comment]
Ah, I didn't see the Create method, I copied the StaticFileRouteHandler as a template in my external code, and it used the constructor, so I didn't look deeper into that. I'll check out the Create method, that may solve that (but I think the StaticFileRouteHandler should also use the Create methods)

**Comment by tomkuijsten** [comment]
I'll reconsider the Create methods, I don't see the added value with eg overloaded constructors. It's probably a left over from another pattern I used. Let me dive into this, you could use the Create methods in the meanwhile, they will be marked Obsolete if we decide to move to overloaded constructors.

**Comment by HakanL** [comment]
I don't care much if you're using constructors or Create methods, but I think it makes sense to use the same pattern throughout the code, even inside the same assembly even if internals are available.

**Comment by HakanL** [comment]
The only thing missing is the MimeTypeProvider, it would be good if that was exposed as well.
