### ISSUE TITLE
HTML file doesn't send http contenttype header (beta2)

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#50]
With current nuget package (beta 2), if you host a html file, there is no contentType header send as response. This works fine in IE and Edge, but doesn't work in chrome/safari. The new implementation with the static MIME list solved this problem, but I'm curious why the value of IFile.ContentType isn't set.

Could be a fault on my side, that's what I expect anyway. But still good to look into.

**Comment by Jark** [comment]
I had a look into this while doing the change (a lot of googling) and it seems that the underlying file system for the RPI doesn't have the mime type information available. 
I also couldn't find a way to add the mime types to the RPI wholesale, it might be worth checking this a few builds along and see if it's a bit more reliable.

**Comment by tomkuijsten** [comment]
You mean that the IFile.ContentType is never set?

**Comment by Jark** [comment]
The IFile.ContentType uses StorageFile.ContentType underneath, StorageFile.ContentType is set to "" on raspberry pi, but works fine when you run it on windows 10.

**Comment by tomkuijsten** [comment]
Hmm ok that explains a lot. Thanks for the info. The dictionary is used now as primary source, the IFile.ContentType as a fallback scenario. I'm fine with closing this issue, agree?

**Comment by Jark** [comment]
Yup, I agree, we can revisit when things change.
