### ISSUE TITLE
How can I get raw body data of http request?

### ISSUE THREAD

**Issue by liudanking** [tomkuijsten/restup#54]
Restup is awesome.
I plan to send an image data to restup server and put the image data in http request body.
I find that restup decode data as json/xml format by default.
So how can I access raw body data to achieve it?

**Comment by Jark** [comment]
Hello @liudanking,

Are you designing a rest api or are you designing something custom? Sounds like you're doing the latter, if so you'll probably want to implement [IRouteHandler](../blob/master/src/WebServer/Models/Contracts/IRouteHandler.cs) yourself. 

You can then send a response back using [HttpServerResponse.Create](https://github.com/tomkuijsten/restup/blob/master/src/HttpMessage/HttpServerResponse.cs#L36) in your IRouteHandler.

Hope this helps,

Jark

**Comment by liudanking** [comment]
Hi @Jark 

I will have a look of `IRouteHandler`. Many thanks!

**Comment by Jark** [comment]
No problems, if there are any issues with using IRouteHandler, feel free to open a new issue.
