### ISSUE TITLE
About error in Restup reference after installed

### ISSUE THREAD

**Issue by escape2here** [tomkuijsten/restup#59]
Hi guys,

i am a newbie and have a question:

after installed Restup in my VS2015 IDE with "Nuget package manager"  if i click on  "Restup" icon Reference in my solution Explorer a error was displayed:

This project cannot be viewed in the object browser because it is unavailable or not yet built. Please ensure that the project is available and built.

Is it a fatal error ? If yes whats i wrong ?

Thanks in advance.

**Comment by Jark** [comment]
Hi @escape2here,

Have you tried building your project? 

When you build your project all NuGet package references are pulled in and after that the error should disappear.

Let me know if this solves it or if you have any other questions.

Cheers,

Jark

**Comment by escape2here** [comment]
Hi Jark,

thanks for your reply. Yes i have built it but the problem still occurred, see a attached screenshot.

Whats i wrong ?

Thanks in advance.
![screenshot](https://cloud.githubusercontent.com/assets/18579028/14706713/a9a8b0e8-07c0-11e6-9aed-79c08e1e8548.jpg)

**Comment by Jark** [comment]
Hey Escape2here,

Looks like there's something funky going on with Windows Universal references... 

If you right-click on Restup and then click "View in object browser" you should be able to explorer the library.

Cheers,

Jark

**Comment by escape2here** [comment]
Hi Jark,
i don't see anything .... :(

![screenshot2](https://cloud.githubusercontent.com/assets/18579028/14707317/61c14476-07c4-11e6-95ba-548a90e8d6f6.jpg)

**Comment by Jark** [comment]
Did you right-click on restup and choose "View in object browser" ?

Here's what I did:

![viewrestupinobjectbrowser](https://cloud.githubusercontent.com/assets/754147/14707882/fd39ca14-07be-11e6-90bd-5c3db73ded06.gif)

Cheers,

Jark

**Comment by escape2here** [comment]
Hi Jark,

if i click dx on "Restup" reference i have only "Proprieties".

I use VS2015 update 1

Thanks.
![screenshot3](https://cloud.githubusercontent.com/assets/18579028/14710370/69c941c6-07d5-11e6-8341-af803f08cfb5.jpg)

**Comment by jasonmalinowski** [comment]
Just a heads up, this is a known issue with Visual Studio NuGet references when your project has a project.json file in it. We're tracking it over at dotnet/roslyn#10685

**Comment by escape2here** [comment]
Thanks @jasonmalinowski.

**Comment by Jark** [comment]
Thanks @jasonmalinowski, clears this issue up :)

@escape2here, just wanted to confirm that this doesn't stop you from using restup, it will just be a bit harder to figure out what to use.

The wiki: https://github.com/tomkuijsten/restup/wiki

and the sample projects in (HeadedDemo/HeadlessDemo) https://github.com/tomkuijsten/restup/tree/master/src

Cheers,

Jark

**Comment by escape2here** [comment]
Hi Jark,
absolutely not :)

Now i am working on it and seeing the sample project.

Thanks.

**Comment by tomkuijsten** [comment]
Can this issue be closed?

**Comment by tomkuijsten** [comment]
Read the whole thread, looks like this can be closed.
