### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#62]
Looks like it's pretty simple to implement this, take a look at this implementation:

https://github.com/sensaura-public/iotweb

**Comment by ummarbhutta** [comment]
Any example how we can add support of Websocket in restup?

**Comment by tomkuijsten** [comment]
You can take a look at https://github.com/sensaura-public/iotweb. To make it work in restup, we would need some changes in the RouteRegistration to allow a route to access input/output streams.

**Comment by ummarbhutta** [comment]
Thanks for sharing the link, The problem is I am already using the **restup** on my WindowsIoT platform, and I couldn't extract any useful information from the link you shared, It doesn't have any example. So what I am looking for is a way to integrate the Websocket support in **restup**, any help on this?

**Comment by tomkuijsten** [comment]
We're (@Jark and myself) currently busy with another feature. This is not planned for the next stable release. Another usefull github project would be the [microsoft sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebSocket). In restup we should probably change or overload the [RegisterRoute](https://github.com/tomkuijsten/restup/blob/master/src/WebServer/Http/HttpServer.cs#L52) to allow the route to read and write the stream.

**Comment by MaklaCof** [comment]
Are there any plans to support WebSocket server?

**Comment by ummarbhutta** [comment]
I think [IotWeb](https://github.com/sensaura-public/iotweb) is a good option if you want to use websockets on Windows IoT.

**Comment by tomkuijsten** [comment]
Not planned
