### ISSUE TITLE
Allow adding header values from the controller

### ISSUE THREAD

**Issue by stevegg** [tomkuijsten/restup#65]
I have  a use case where I want to use a REST api to return an image. Right now there's no way (that I could find) to modify the content-type header before it's returned to the caller.  What would be great is something like:

```
return(GetResponse)new GetResponse(GetResponse.ResponseStatus.OK, result)
                       .addHeader("Content-Type", "image/jpeg");
```

It would also be useful to have some way to add headers to all responses (event?).  This would allow adding things like CORS headers.  e.g. : 

```
.addHeader("Access-Control-Allow-Origin", "*")
.addHeader("Access-Control-Allow-Headers", "x-requested-with ");
```

**Comment by stevegg** [comment]
I created a pull request (https://github.com/tomkuijsten/restup/pull/66) with some code to implement the above.

**Comment by stevegg** [comment]
Did another pull request for Development branch (https://github.com/tomkuijsten/restup/pull/68) (What I should have done first).  Please ignore #66

**Comment by Jark** [comment]
`1.` I don't think it's a good idea to return an image through the rest api. I also had a look at https://github.com/tfredrich/RestApiTutorial.com and I can't find any reference to returning an image as a response. 

Can you provide us with your use case for wanting to do this?

I would implement a custom IRouteHandler to return an image, you have got a maximum amount of flexibility there and it seems you might need that.

`2.` I think we should definitely add support for CORS headers, but that should be an integral part to the webserver and should be implemented as a feature on the HttpServer class (or on the handlers). The user shouldn't have to manually add headers inside the rest controller.

**Comment by stevegg** [comment]
My specific use case is that I aggregate dynamic images from a set of cameras on my network.  The images are displayed in a web interface as well as stored in a database at regular intervals.

As for not needing to add headers....I've heard that comment before.  It was a common refrain during the development of Jersey for Java.  In the end there are many many reasons to add headers.  Whether it's custom headers ("X-" prefix) or changing caching information etc...  

CORS should definitely be a core part of the platform.

**Comment by Jark** [comment]
`1` Your use case does not seem to be a good fit for a REST api. In your case I would implement a custom IHttpHandler to return the images that you want. Should be fairly simple to do and would give you the maximum of flexibility that you need and will work now (without any changes needed to restup).

If we want to support your use case (returning different content than json / xml), then we should do that in a more structured way then having to set the content-type header (which might be overriden by restup at a later point) and having to hack the serializer. 

My solution would be to have the Response methods that support a body, override a common base that would have something like a IRestContent interface that would have some configurability (e.g. setting the serialiser to none and explicitly specifying the content-type). I would very much advocate against making the I<method>Response concrete implementations mutable.

`2` I agree that specifying custom headers should be a possibility, but restup should definitely have support for things like CORS, caching, authorisation and any other standard headers.

**Comment by stevegg** [comment]
While I disagree it's probably not worth arguing over.  There are a good many examples of returning images from a REST service....BUT....what you're saying makes sense as well.

Will attempt to implement it with an IHttpHandler.  I'm guessing this would mean a custom route to point to my image resource.  Will this allow me to pass an ID?

In my case the cameras are a resource (basic DB crud using SQLIte)

GET /api/camera/{id}
PUT /api/camera
POST /api/camera
DELETE /api/camera

I then access the cameras to pull snapshots.

GET /api/camera/{id}/snapshot - Current Live image
GET /api/camera/{id}/snapshot?time={datetime}&duraction={duration}

BTW, The current URL handling doesn't support the above very well. 

Steve

**Comment by Jark** [comment]
Can you point me to any rest document which recommends your approach?

This is the pattern I would suggest using:

```
PUT /api/camera -> returns location /snapshots/<guid/id/name>
```
and then you would have a IHttpHandler listening on /snapshots, all incoming requests would come in with the url `/<guid/id/name>` which you would then map directly to a db query / cache. 

Similarly your `GET /api/camera/{id}/snapshot` request would return the image url for your page to load. The ImageHttpHandler would be very sample and all the main logic would be in your rest api.


As I've said before I do agree with being able to specify headers to the responses, I've added a pull request with a possible solution that doesn't make the I<method>Responses concrete implementations mutable (and added a test). I do need to add tests for the constructors of the different responses. (#71) Also, I'm wondering if a request factory would be a better solution then having so many overloads of the same constructor (or use optional constructor arguments?).

However to satisfy your use case you would need a second feature, to be able to specify that you don't want your content serialised, or that you possibly want a specify type of serialisation. I will raise an issue for it and then we can see if we will want to do this. @tomkuijsten what do you think about the above?

**Comment by stevegg** [comment]
At the risk of prolonging the debate (Honestly I think what your suggesting will work fine)... You need to only do a google search for "REST service with images".  In fact I see common use cases returning all sorts of binary data...is it a good idea....hmmmmmm

I guess I'd like to understand why you believe that returning an image in an API call is a bad thing?  If you could point me to something that explicitly says "You should never return anything but JSON/XML (Don't forget YAML) from a REST api" that might be helpful.

I like the approach of adding the headers as a Dictionary in the constructor.  I worry though that this pattern may not be supportable for anything beyond headers though.  If the next guy like me comes along and says "I'd like access to <insert response property here>"? 

As for the serializer....could there be a mechanism to specify a custom serializer?  Maybe register a serializer for a route?

```
var myCustomSerializer = new CustomContentSerializer();
httpServer.RegisterRoute("api", restRouteHandler, myCustomSerializer);
```

**Comment by tomkuijsten** [comment]
You can set headers in your response object (#75). If it's not sufficient, please, add another issue so we can talk about it separate from the header discussion.
