### ISSUE TITLE
Support Cross-Origin Resource Sharing (CORS)

### ISSUE THREAD

**Issue by Jark** [tomkuijsten/restup#70]
We should support CORS in restup on a HTTPServer level. 

HTTP spec: https://www.w3.org/TR/cors/
MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

For our first implementation we should just support simple cross-origin request. After that we can do the work to support preflight requests as well.

Whoever picks this up, please make a (simple) design first since it will most likely touch multiple parts of the HttpServer, and post it here.

**Comment by tomkuijsten** [comment]
This is supported as custom implementation through #77 and #75
