### ISSUE TITLE
Support JSONP Wrapper

### ISSUE THREAD

**Issue by WattsC-90** [tomkuijsten/restup#72]
Support JSONP Function Wrapper for cross-domain calls.
good information on the requirement can be found here: http://stackoverflow.com/questions/3295692/does-jsonp-require-server-modifications

JSONP requires server side support unfortunately, would be great if RestUp supported it

**Comment by WattsC-90** [comment]
This may be made redundant by the issue Jark opened about CORS support..  #70 
Apparently JSONP is oldhat..

**Comment by tomkuijsten** [comment]
My understanding too. CORS will be available as custom implementation when #77 is done.
