### ISSUE TITLE
Add an IHttpRequestFilterAttribute

### ISSUE THREAD

**Issue by Jark** [tomkuijsten/restup#77]
I propose to add an IHttpRequestFilterAttribute which should allow you to reject certain calls or send a different request back. With this we could easily add CORS or authorisation support.

You should be able to apply this attribute on methods and on the class, the class one will be triggered first, and then the method level ones.

**Comment by tomkuijsten** [comment]
I would suggest a more "low level" approach. Like you said before, you shouldn't mangle different abstraction levels. I would expect some interface when the route gets registered. Maybe a ```BeforeSendReply``` and ```AfterReceiveRequest``` like the [IDispatchMessageInspector](https://msdn.microsoft.com/en-us/library/system.servicemodel.dispatcher.idispatchmessageinspector(v=vs.110).aspx).

**Comment by Jark** [comment]
I agree, it looks like we want something similar to ActionFilters in asp net core --> https://damienbod.com/2015/09/15/asp-net-5-action-filters/

**Comment by tomkuijsten** [comment]
Busy on the feature branch for this. @Jark could you take a look and let me know if you agree on how I intent to implement this feature.

**Comment by Jark** [comment]
Hi @tomkuijsten, 

There's a couple of questions/remarks I have about the design:

1. Why did you choose to put the IMessageInspector functionality in HttpServer? I thought the idea was to be able to add an attribute to the controllers / methods in rest land and do the BeforeExecuting / AfterExecuted logic like asp .net does it (https://msdn.microsoft.com/en-us/library/gg416513(v=vs.98).aspx)
2. Please, please, please don't expose the internal MutableHttpServerRequest object to the IMessageInspectors, we should really have some kind of interface / other context type class which specifies exactly what a IMessageInspector can access. If we don't do this then we can never modify the internal MutableHttpServerRequest without breaking the IMessageInspectors possibly. 
3. Why did you merge/conflate the functionality of keeping routes and storing message inspectors for a certain route, I assume this is just for the prototype? I would either keep them as separate sets or encapsulate the list of message inspectors in the RouteRegistration object (or a new RouteRegistrationWithMessageInspectors).
4. Why the correlation object in the IMessageInspector interface? What can that be used for?

I think it would be good to formulate a couple of hard use cases that we can set up as a test case, a few that come to mind are:
  1. be able to read out the headers, notice the API authorisation key is wrong and immediately send an authorisation response back (without executing the method / request).
  2. after the method / handler has finished executing, add the origin headers

minor side issue:

1. I noticed you moved the listener creation / event attachment to the Start method. Nothing wrong with that, but I do think we should remove the Stop method since all it does is calling dispose. If I were to use this myself I would call HttpServer.Stop()  and then Dispose(), which would throw because there's no null check around _listener in the Dispose method.

Anyway, this is my 2 cents, looking forward to your reply  :)

**Comment by tomkuijsten** [comment]
1. Well... you kind of agreed on that in this very discussion :) I like the idea of a message inspector over attributes, The inspector is on another abstraction level, which makes sense as you are mangling with low level data. With attributes you have to tag each and every class/method, which is a bit cumbersome if you need something like CORS for every API call. The way I see it; you want all or a specified group of API calls to have some low level behavior. You group these calls in a RouteHandler and attach the inspector. 

Another thing I don't really like about attributes is it's discoverability, or lack of. I think an overloaded method with inspectors is more visible then an attribute.

Apologies if I wasn't clear about this idea.

2. Good idea. However, the intention here is to expose everything. The inspector should have full access. I could extract an interface of the mutable class to prevent our internal changes from interfering with 3th party inspectors.

3. Agree

4. That's how the [IDispatchMessageInspector](https://msdn.microsoft.com/en-us/library/system.servicemodel.dispatcher.idispatchmessageinspector(v=vs.110).aspx) is working as well. To pass info from AfterReceiveRequest to BeforeSendResponse.

Use cases; agree, let's discuss after we reached consensus about the design.

Minor issue:
1. I do think the Stop method makes sense. This is how eg File works as well. You can Close and Dispose it. The Close however does the dispose already. I would suggest to make the dispose fool proof.

**Comment by tomkuijsten** [comment]
Holiday is over and I want to allow CORS as I need it as well for our webapp. I did some reading of CORS and if I understand correctly we have to support the OPTIONS (preflight) method to support a POST with xml or json data. I think we should make a list of changes we need to support the preflight CORS functionality.

**Comment by Jark** [comment]
@tomkuijsten Have a look at https://github.com/tomkuijsten/restup/issues/70 and the links I posted in there :) The spec contains the needed information to create the functionality.

**Comment by tomkuijsten** [comment]
Thanks for the links. I do get the request more often for CORS support. My initial idea was to enable other developers to access header information and let them implement this specific scenario. But I must admit that I'm not so sure about that approach anymore, looks like a broadly used pattern which should be part of our core. What do you think?

**Comment by Jark** [comment]
Yeah, let's add it to the core support. Think it's quite important to have generally speaking.

I have some free programming time coming up this weekend, if you don't mind I can probably whip something up?

**Comment by tomkuijsten** [comment]
I don't mind Go your gang... :)

**Comment by Jark** [comment]
Only had an hour yesterday, but managed to get cors working. All very hacky right now, needs to have some kind of permissions set added to it + tests still. Will do a pull request once I've got something working. Here is the code if you're interested -> https://github.com/jark/restup/tree/feature-add-support-for-cross-origin-headers

**Comment by tomkuijsten** [comment]
Am I correct that these are only the headers? If so, what's your plan for supporting CORS out-of-the-box. I see a couple of scenario's:

1. We expose the headers and make some kind of interception possible to send a response without a request to a REST controller
2. We automate everything. We write the interceptor ourselves, see what verb is being ask for, check the REST controllers to see if we support that and have some policy (configurable or not)  to determine authorized request url's, headers etc.
3. We create an IOptionResponse, expose CORS information somehow and the user should do all the work

Any other scenario's you can think of?

**Comment by Jark** [comment]
First, it might be worth reading `https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests`, it's really good at explaining CORS.

I've hacked it together so that all the bits are there to support both simple and pre-flighted requests (so the ones that send an options request for the same exact url) so it is fully working. Some of the intricacies are still missing, but I'll take a look at every one of them once I write some unit tests around the simple, pre-flighted and credentials scenarios.

Haven't thought too much about the exact scenario I wanted to implement, but right now scenario 2 sounds like the best option. 

The exact scenario I'm going to implement as a first cut is a "MessageInspector" like implementation so `httpServer.AddMessageInspector(new CorsMessageInspector(new List<string>("allowedorigin1", "allowedorigin2")))` but not actually defining an interface yet for the MessageInspector.

After I've done that and written tests and so on we can then finish the pull request (review, etc.) and then decide to:
- have more configuration like allowed methods, allowed headers
- finish the implementation of IHttpMessageInspector and 

Option 3 is a bit odd I think, because the user would need to mirror every method where they would want to allow Cors. 99% of the time the use case is to turn it on for the whole domain anyway.

**Comment by tomkuijsten** [comment]
Closed with PR #86
