### ISSUE TITLE
Support charset in content-type

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/restup#8]
The charset information in the content-type header is ignored now, should use it to decode the body.

Content-Type: application/json; charset=UTF-8

**Comment by tobiasstraub** [comment]
Do you work on this feature? - If you need my Contribution you can add me as assignee.

**Comment by tomkuijsten** [comment]
I'm not working on this, so if you want, you can implement it. Just let me know.

**Comment by tomkuijsten** [comment]
I've done some extensive rework which included the charset, it should work properly now,
