### ISSUE TITLE
Unable to deployt to IoT on Pi3

### ISSUE THREAD

**Issue by Dameon13th** [tomkuijsten/restup#81]
I copied the headless application, modified it, and tried deploying it to my IoT device. 
It fails to install with the following error. Failure reason: Failed to start deployment. Failure text: Package failed updates, dependency or conflict validation. (0x80073cf3)

Device Model:  Raspberry Pi 3 
OS Version:  10.0.14366.0

**Comment by tomkuijsten** [comment]
Tried deploying on the pi3 with ffu 14366, but it works fine.

Could you add some more details, eg VS version, OS version etc

**Comment by dm-CaT** [comment]
I have restup working on 13766 without any doubts in headless application.

**Comment by dm-CaT** [comment]
Can you try to reinstall Windows Core and then install your application on clean OS?

**Comment by psykad** [comment]
Have you tried deploying from a fresh copy of the source? How are you deploying it?

**Comment by tomkuijsten** [comment]
@Dameon13th I consider this as fixed as there is no response. If you still encounter the problem after the suggestions (thanks @psykad and @dm-CaT ), you can reopen the issue.
