### ISSUE TITLE
Question: Will Restup support POSTing files?

### ISSUE THREAD

**Issue by mbrewerton** [tomkuijsten/restup#84]
Hi, I've been trying to find a way to post file data to my IoT device, and I was just wondering if Restup will provide that functionality? That's the core of my project so it's a game-changer if it can!

Apologies if this is a silly question!

**Comment by tomkuijsten** [comment]
It's not a silly question as REST doesn't imply any particular data format (or even carrier). However, I'm not planning to support this. It would mean a serious amount of work and I think most of our users are satisfied with the json and xml options.
