### ISSUE TITLE
Can you add a sample project?

### ISSUE THREAD

**Issue by capcata** [tomkuijsten/restup#89]
I can't build any code because I can't figure out which references shuld I use.

The wiki samples are missing:
https://github.com/tomkuijsten/restup/wiki/Samples

Thanks
Guido

**Comment by micharichter** [comment]
If you can wait until Thursday I could create a dsimple console application. Please let me know (Tom) If you want me to do this. 

Regards Micha

**Comment by tomkuijsten** [comment]
Fixed the links, thanks for pointing it out to me. But even without any samples, you should get going by just reading the [one pager](https://github.com/tomkuijsten/restup/wiki/One-pager).

@micharichter thanks for the help, I would say the existing samples will do, If you decide to create another sample, I would suggest to extend the existing one ([HeadedDemo](https://github.com/tomkuijsten/restup/tree/master/src/HeadedDemo) and [HeadlessDemo](https://github.com/tomkuijsten/restup/tree/master/src/HeadlessDemo)) and create a PR?

**Comment by micharichter** [comment]
Hi Tom, 
my proposal:  I`m working on a project to switch on / off GPIO ports of my RaspberryPi at home via an Azure hosted WebApplication. I`m using your restup to handle the requests on my pi. After finishing this , I want to publish this project here on Github. We could link this on this page if you like.

**Comment by tomkuijsten** [comment]
Post a link when your done, we could add a wiki page with projects using restup. Thanks in advance.

**Comment by capcata** [comment]
Thanks a lot.
Sorry, I've not touched visual studio in 10 years. I'm trying to do my best.
I'm working on a two-way Json comunication Arduino-RPi.

**Comment by tomkuijsten** [comment]
Not a problem at all. As I said before, the pi part is pretty well explained in the one pager. I can't help you with the arduino part, don't have any experience in that area.

**Comment by tomkuijsten** [comment]
Will close this issue. Please, open a new one (@micharichter) when your project is available.
